apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  namespace: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - name: glpi
        image: diouxx/glpi:latest
        ports:
        - containerPort: 80
        env:
        - name: GLPI_DB_HOST
          value: "glpi-db-service"
        - name: GLPI_DB_USER
          value: "glpiuser"
        - name: GLPI_DB_PASSWORD
          value: "glpipassword"
        - name: GLPI_DB_NAME
          value: "glpidb"
        volumeMounts:
        - name: glpi-storage
          mountPath: /var/www/html
      volumes:
      - name: glpi-storage
        persistentVolumeClaim:
          claimName: glpi-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-pvc
  namespace: glpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
