apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-db
  labels:
    app: glpi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi-db
  template:
    metadata:
      labels:
        app: glpi-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "glpidb"
        - name: MYSQL_USER
          value: "glpiuser"
        - name: MYSQL_PASSWORD
          value: "glpipassword"
